export default [
  "Ah Moharram",
  "Al-Battar",
  "Al-Jazeera",
  "Al-Watan Headlines",
  "Ara Aqeeq",
  "Arabics",
  "Basim Marah Beh",
  "Boutros Art",
  "Cocon",
  "Diwan",
  "Edilbi Souria",
  "Fanni",
  "Farsi",
  "Hacen Saudi Arabia",
  "Hamada",
  "Hayah",
  "Ibtisam",
  "Khat Thuluth",
  "Khayal",
  "Maghribi Assile",
  "Naskh",
  "Noora",
  "Sadiyah",
  "Sardar Hoor",
  "Thuluth",
  "Uthmanic Hafs",
];
